// @generated drizzle-zero signature:sha256:c82d77542e8e79399aeb9b84bf63cb860919475afd48b37d6662ce4949f314db
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type {Row} from '@rocicorp/zero';
import {createBuilder} from '@rocicorp/zero';

const albumsTable = {
  name: 'albums',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    title: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    artistId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'artist_id',
    },
    releaseYear: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'release_year',
    },
    coverArtUrl: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'cover_art_url',
    },
    createdAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
  },
  primaryKey: ['id'],
} as const;
const artistsTable = {
  name: 'artists',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    genre: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    bio: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
  },
  primaryKey: ['id'],
} as const;
const fansTable = {
  name: 'fans',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
  },
  primaryKey: ['id'],
} as const;
const favoritesTable = {
  name: 'favorites',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    fanId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'fan_id',
    },
    albumId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'album_id',
    },
    createdAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
  },
  primaryKey: ['id'],
} as const;
const albumsRelationships = {
  artist: [
    {
      sourceField: ['artistId'],
      destField: ['id'],
      destSchema: 'artists',
      cardinality: 'one',
    },
  ],
  favorites: [
    {
      sourceField: ['id'],
      destField: ['albumId'],
      destSchema: 'favorites',
      cardinality: 'many',
    },
  ],
} as const;
const artistsRelationships = {
  albums: [
    {
      sourceField: ['id'],
      destField: ['artistId'],
      destSchema: 'albums',
      cardinality: 'many',
    },
  ],
} as const;
const fansRelationships = {
  favorites: [
    {
      sourceField: ['id'],
      destField: ['fanId'],
      destSchema: 'favorites',
      cardinality: 'many',
    },
  ],
} as const;
const favoritesRelationships = {
  fan: [
    {
      sourceField: ['fanId'],
      destField: ['id'],
      destSchema: 'fans',
      cardinality: 'one',
    },
  ],
  album: [
    {
      sourceField: ['albumId'],
      destField: ['id'],
      destSchema: 'albums',
      cardinality: 'one',
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    albums: albumsTable,
    artists: artistsTable,
    fans: fansTable,
    favorites: favoritesTable,
  },
  relationships: {
    albums: albumsRelationships,
    artists: artistsRelationships,
    fans: fansRelationships,
    favorites: favoritesRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "albums" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Album = Row<(typeof schema)['tables']['albums']>;
/**
 * Represents a row from the "artists" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Artist = Row<(typeof schema)['tables']['artists']>;
/**
 * Represents a row from the "fans" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Fan = Row<(typeof schema)['tables']['fans']>;
/**
 * Represents a row from the "favorites" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Favorite = Row<(typeof schema)['tables']['favorites']>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema;
  }
}
